import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
//import Navbar_28 from '@/components/Navbar_28';
import Navbar_28 from './demo/_components/Navbar_28';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar_28 />
        {children}
      </body>
    </html>
  );
}
